name: Release

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Get App token
        id: get-app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.get-app-token.outputs.token }}
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.5"

      - uses: actions/cache@v1
        with:
          path: /home/runner/go/pkg/mod
          key: go-mod

      - uses: goreleaser/goreleaser-action@v2
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
